sudo: required
services:
  - docker

before_install:
  - docker build -t react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true react-test npm test

after_success:
  - docker build -t qinfengwu90/multi-client ./client
  - docker build -t qinfengwu90/multi-nginx ./nginx
  - docker build -t qinfengwu90/mulit-server ./server
  - docker build -t qinfengwu90/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push qinfengwu90/multi-client
  - docker push qinfengwu90/multi-nginx
  - docker push qinfengwu90/mulit-server
  - docker push qinfengwu90/multi-worker